In [1]:
%cd ../..

o:\dev\_digisound\IBUKI_project\ibuki


In [2]:
from neurogen.data_processing.datasets import SimpleDilatedWavHandler
from neurogen.utils import wav16_to_onehot
import torch
from torch.utils.data import DataLoader

In [13]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

wav_path = './datasets/wav/wwolves/ww_resurge.wav'
patch_size = 32
n_patches = 128
dilation_depth = 5

n_classes = 8
dataset = SimpleDilatedWavHandler(wav_path, 
                                  patch_size=patch_size, 
                                  n_patches=n_patches,
                                  dilation_depth=dilation_depth,
                                  device=device)
batch_size = 32
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=False)

In [14]:
for bdx, (sample, target, recept_data) in enumerate(dataloader):
    if torch.abs(target.sum()) < 500:
        print(target)
        targ_oh = wav16_to_onehot(target, n_classes=n_classes, do_mu=False)
        print(targ_oh)
        target_rec = torch.argmax(targ_oh, dim=1)
        print(target_rec)
        break

tensor([-20440, -22266, -23196, -19701, -10574,  -6348,  -3158,  -2173,   -487,
          3363,   4230,   3041,   3758,   3695,   4310,   2128,   1691,   5273,
          4043,   3072,  10387,   5237,  -4901,  10287,  21479,  21103,  14075,
          6905,    828,  -3767,  -6769,  -5612], device='cuda:0',
       dtype=torch.int16)
tensor([1, 1, 1, 1, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 3, 5,
        6, 6, 5, 4, 4, 3, 3, 3], device='cuda:0')
tensor([[0, 1, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0