In [15]:
import numpy as np
import torch

In [29]:
patch_size = 4
max_dil_deg = 3
max_dil_size = 2**max_dil_deg
n_patches = 3

a = np.arange(max_dil_size * (n_patches - 1) + 1).astype(np.float32)
a = np.repeat(a, patch_size) 
#a += np.random.randn(*a.shape) * 0.1
t_a = torch.from_numpy(a)
t_a_u = t_a.unfold(0, patch_size, patch_size)
print(t_a_u)

tensor([[ 0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.],
        [11., 11., 11., 11.],
        [12., 12., 12., 12.],
        [13., 13., 13., 13.],
        [14., 14., 14., 14.],
        [15., 15., 15., 15.],
        [16., 16., 16., 16.]])


In [33]:
for dil_deg in range(max_dil_deg+1):
    dil = 2**dil_deg
    t_a_selected = t_a_u[::dil, :][-n_patches:]
    print(t_a_selected.flatten())

tensor([14., 14., 14., 14., 15., 15., 15., 15., 16., 16., 16., 16.])
tensor([12., 12., 12., 12., 14., 14., 14., 14., 16., 16., 16., 16.])
tensor([ 8.,  8.,  8.,  8., 12., 12., 12., 12., 16., 16., 16., 16.])
tensor([ 0.,  0.,  0.,  0.,  8.,  8.,  8.,  8., 16., 16., 16., 16.])
